name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
      - 'develop'
  workflow_dispatch:

env:
  APP_NAME: geniro-web
  NODE_VERSION: 22
  DOCKER_IMAGE: docker.io/razumru/geniro-web

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-22.04
    name: Version packages
    outputs:
      release_created: ${{ steps.semantic.outputs.release_created }}
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate_token
        with:
          app_id: ${{ secrets.BOT_APPLICATION_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          HUSKY: 0

      - name: Prepare repository
        run: |
          git config user.email "ci@geniro.io"
          git config user.name "Geniro Bot"

      - name: up version
        id: semantic
        run: |
          OUTPUT=$(pnpm run up-versions)

          echo $OUTPUT

          if echo "$OUTPUT" | grep -q "no new version is released"; then
           echo "release_created=false" >> $GITHUB_OUTPUT
          else
           echo "release_created=true" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
  build-and-push:
    runs-on: ubuntu-22.04
    name: Build And Push
    needs: [version]
    if: ${{ !contains(needs.version.result, 'failure') && needs.version.outputs.release_created == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          git fetch --tags --force --prune

          TAG=$(git tag --list "@${{ env.APP_NAME }}/${{ env.APP_NAME }}@*" | sort -V | tail -n 1 | awk -F'@' '{print $3}')
          if [[ -z "$TAG" ]]; then TAG="0.0.0"; fi

          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
            VERSION_POSTFIX="latest"
          else
            VERSION_POSTFIX="develop"
          fi

          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "version_postfix=$VERSION_POSTFIX" >> "$GITHUB_OUTPUT"
          echo "final_tag=$TAG-$VERSION_POSTFIX" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: './Dockerfile'
          push: true
          provenance: false
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.version_postfix }}
            ${{ env.DOCKER_IMAGE }}:${{ steps.version.outputs.final_tag }}
